export const BOOKMARKS_QUERY = 'bookmarks'
export const FAV_BOOKMARKS_QUERY = 'favorite-bookmarks'
export const FOLDERS_QUERY = 'folders'
export const TAGS_QUERY = 'tags'
export const PROFILE_QUERY = 'profile'
export const FOLDER_ITEMS_QUERY = 'folder-items'
export const FOLDER_ITEM_COUNT_QUERY = 'folder-item-count'
export const TAG_ITEMS_QUERY = 'tag-items'
